go.property("distance", 100)
go.property("axis", 0) -- 0 for horizontal / x-axis, 1 for vertical / y-axis
go.property("speed", 15)
function init(self)
	local to = 0
	local anim_dir = "position.x"
	local pos = go.get_position()
	to = pos.y + self.distance
	anim_dir = "position.y"
	local duration = self.distance / self.speed
	go.animate(".", anim_dir, go.PLAYBACK_LOOP_PINGPONG, to, 
	go.EASING_INOUTQUAD, duration)
end