go.property("distance", 50)

local u = 0

win_message = {"The Frogs are saved!\nThe ocean generates over half of the oxygen we breathe", 
"The Frogs are saved!\nThe ocean contains more than 97% of the world’s water", 
"The Frogs are saved!\nA healthy ocean regulates climate and reduce climate change impacts", 
"The Frogs are saved!\nThe ocean provides at least one fifth of the animal protein people eat",
"The Frogs are saved!\nThe ocean provides millions of livelihoods that stimulate local and global economies", 
"The Frogs are saved!\nOcean ecosystems contain ingredients for critical medications", 
"The Frogs are saved!\nThe ocean creates an important form of transportation",
"The Frogs are saved!\nThe ocean provides an incredible source of beauty, inspiration, and recreation",
"The Frogs are saved!\nThe ocean supports an incredible diversity of life"}

local SPEED = 10
local DEAD_SPEED = 200

local COLLISION_RESPONSE = hash("collision_response")
local BULLET = hash("bullet")
local rubbish_remaining = 5

function init(self)

end

local function random(x, y)
	u = u + 1
	if x ~= nil and y ~= nil then
		return math.floor(x +(math.random(math.randomseed(os.time()+u))*999999 %y))
	else
		return math.floor((math.random(math.randomseed(os.time()+u))*100))
	end
end

function on_message(self, message_id, message, sender)
	if self.dead then return end
	if message_id == COLLISION_RESPONSE then
		-- turn the bee upside down and make it drop dead!
		-- also flag it as dead and ignore any additional messages
		self.dead = true
		sprite.set_vflip("#sprite", true)
		local pos = go.get_position()
		local duration = pos.y / DEAD_SPEED
		go.cancel_animations(".", "position.y")
		go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INQUAD, duration, 0, function()
			go.delete()
		end)

		msg.post("rubbish#pickup", "play_sound", {delay = 0, gain = 1})
		rubbish_remaining = rubbish_remaining - 1
		msg.post("/hud#rubbish_remaining", "update_rubbish_remaining", {newrubbishremaining = rubbish_remaining})
		print(rubbish_remaining)

		if rubbish_remaining == 0 then
			msg.post("/hud#rubbish_remaining", "update_end_message", {newendmessage = win_message[random(1, 9)]})
			msg.post("/player/audio#bgm", "stop_sound", {delay = 0, gain = 1})
			msg.post("/player/audio#winbgm", "play_sound", {delay = 0.5, gain = 1})
			msg.post("/level#script", "game_complete", {})
		end

		msg.post("/level#script", "water_change", {})
	end
end