go.property("distance", 50)

win_message = {"The ocean generates over half of the oxygen we breathe", 
"The ocean contains more than 97% of the world’s water", 
"A healthy ocean regulates climate and reduce climate change impacts", 
"The ocean provides at least one fifth of the animal protein people eat",
"The ocean provides millions of livelihoods that stimulate local and global economies", 
"Ocean ecosystems contain ingredients for critical medications", 
"The ocean creates an important form of transportation",
"The ocean provides an incredible source of beauty, inspiration, and recreation",
"The ocean supports an incredible diversity of life"}

local SPEED = 10
local DEAD_SPEED = 200

local COLLISION_RESPONSE = hash("collision_response")
local BULLET = hash("bullet")
local rubbish_remaining = 5

function init(self)

end

function on_message(self, message_id, message, sender)
	if self.dead then return end
	if message_id == COLLISION_RESPONSE then
		-- turn the bee upside down and make it drop dead!
		-- also flag it as dead and ignore any additional messages
		self.dead = true
		sprite.set_vflip("#sprite", true)
		local pos = go.get_position()
		local duration = pos.y / DEAD_SPEED
		go.cancel_animations(".", "position.y")
		go.animate(".", "position.y", go.PLAYBACK_ONCE_FORWARD, 0, go.EASING_INQUAD, duration, 0, function()
			go.delete()
		end)

		msg.post("rubbish#pickup", "play_sound", {delay = 0, gain = 1})
		rubbish_remaining = rubbish_remaining - 1
		msg.post("/hud#rubbish_remaining", "update_rubbish_remaining", {newrubbishremaining = rubbish_remaining})
		print(rubbish_remaining)

		if rubbish_remaining == 0 then
			math.randomseed(os.time())
			msg.post("/hud#rubbish_remaining", "update_end_message", {newendmessage = win_message[math.random(1, 10)]})
		end
	end
end